version: '3'
services:
  data_volume:  # 公共数据卷latest
    build: ./data_volume
    container_name: data_volume
    volumes:
      - ${RECORD_PWD}:/data
      - ${CONF_PWD}:/opt/etc
      - ${PRODUCT_PWD}:/opt/project
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CONF_PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - data_volume
    networks:
      - app-net
    restart: always 
    #command:
    #  - 'nginx'
  mongo:  # v4.2
    build: ./mongo
    container_name: mongo
    volumes_from:
      - data_volume
    ports:
      - "27017:27017"
    networks:
      app-net:
        ipv4_address: 170.0.0.7
    restart: always
    command:
      ### --smallfiles option is no longer supported in newer mongodb versions starting from 4.2
      #- '--smallfiles' 
      - '-f'
      - '/opt/etc/mongod.conf'
  redis:  # v6.0
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes_from:
      - data_volume
    restart: always
    networks:
      app-net:
        ipv4_address: 170.0.0.6
    command:
      - '/opt/etc/redis.conf'
  centos:  # centos8
    build: ./centos
    container_name: centos
    volumes_from:
      - data_volume
    networks:
      app-net:
        ipv4_address: 170.0.0.5
    ports:
      - "8004:8004"
      - "8002:8002"
networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 170.0.0.1/16

